### ISSUE TITLE
Build Chain panics router when URI is invalid

### ISSUE THREAD

**Issue by gtfierro** [immesys/bw2#16]
```
[INF] 09:35:18 2016-07-21 chainbuilder.go:171 chain build cache miss
[CRT] 09:35:18 2016-07-21 commands.go:355 CB fail: Invalid URI
panic: Invalid URI

goroutine 475 [running]:
panic(0x10b4180, 0xc8235e2340)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/immesys/bw2/adapter/oob.(*boundFrame).cmdBuildChain.func2(0xc823570f80, 0xc822d0eb20)
        /go/src/github.com/immesys/bw2/adapter/oob/commands.go:356 +0x2a7
created by github.com/immesys/bw2/adapter/oob.(*boundFrame).cmdBuildChain
        /go/src/github.com/immesys/bw2/adapter/oob/commands.go:384 +0x4cc
```

**Comment by immesys** [comment]
Yeah, I'll take a look when I do 2.6 which will likely be after the 8th. There is a list of things

**Comment by samkumar** [comment]
I'm seeing this issue as well. I tried to build a chain for the invalid URI JzFkfWH0JQQuoFZ0UXb8XMI-NJYUnxPGasK7RQKXCWc=/x/d/sd* and my agent crashed.
