### ISSUE TITLE
Cannot run `bw2`

### ISSUE THREAD

**Issue by gtfierro** [immesys/bw2#4]
Installed bw2 from the curl script. I get the following error running `router` or `mkentity`

```
gabe@pantry:~⟫ bw2 router
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x49396c]

runtime stack:
runtime.gothrow(0xa3eef0, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x48bae0, 0xc2080f2d28, 0x0)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080f2d08 sp=0xc2080f2ce0
github.com/immesys/bw2/internal/rocks._Cfunc_init(0xc2080f6018, 0x6)
        github.com/immesys/bw2/internal/rocks/_obj/_cgo_gotypes.go:54 +0x45 fp=0xc2080f2d28 sp=0xc2080f2d08
github.com/immesys/bw2/internal/rocks.Initialize(0xc20802bb90, 0x6)
        /home/gabe/go/src/github.com/immesys/bw2/internal/rocks/iface.go:39 +0x72 fp=0xc2080f2d70 sp=0xc2080f2d28
github.com/immesys/bw2/api.OpenBWContext(0xc20806c300, 0x9bccb0)
        /home/gabe/go/src/github.com/immesys/bw2/api/bosswave.go:105 +0xa3e fp=0xc2080f2f70 sp=0xc2080f2d70
main.actionRouter(0xc2080ee0e0)
        /home/gabe/go/src/github.com/immesys/bw2/bw.go:249 +0x82 fp=0xc2080f3010 sp=0xc2080f2f70
github.com/codegangsta/cli.Command.Run(0x9c3750, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa493b0, 0x30, 0x0, ...)
        /home/gabe/go/src/github.com/codegangsta/cli/command.go:118 +0x1044 fp=0xc2080f3410 sp=0xc2080f3010
github.com/codegangsta/cli.(*App).Run(0xc2080e8000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /home/gabe/go/src/github.com/codegangsta/cli/app.go:158 +0xd0c fp=0xc2080f36f8 sp=0xc2080f3410
main.main()
        /home/gabe/go/src/github.com/immesys/bw2/bw.go:240 +0x2699 fp=0xc2080f3f98 sp=0xc2080f36f8
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080f3fe0 sp=0xc2080f3f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080f3fe8 sp=0xc2080f3fe0

goroutine 5 [semacquire]:
sync.(*Cond).Wait(0xc20803a800)
        /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc20806c000, 0x4c6300)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc20806c000)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 6 [semacquire]:
sync.(*Cond).Wait(0xc20803a9c0)
        /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc20806c100, 0x0)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc20806c100)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 7 [semacquire]:
sync.(*Cond).Wait(0xc20803b140)
        /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc20806c200, 0x0)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc20806c200)
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
        /home/gabe/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 8 [sleep]:
github.com/immesys/bw2/internal/core.func·002()
        /home/gabe/go/src/github.com/immesys/bw2/internal/core/terminus.go:186 +0x41
created by github.com/immesys/bw2/internal/core.CreateTerminus
        /home/gabe/go/src/github.com/immesys/bw2/internal/core/terminus.go:196 +0x22e

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by gtfierro** [comment]
I had an old version on the system. Removing that fixed this error, but it might be nice if the install script asked if I wanted to continue if it detected the previous command, instead of starting anyway and then getting the wrong bw2 binary.
